CREATE TABLE IF NOT EXISTS worker (
id SERIAL PRIMARY KEY,
name VARCHAR (200) NOT NULL,
department VARCHAR (200) NOT NULL
);

CREATE TABLE IF NOT EXISTS head (
id SERIAL PRIMARY KEY,
department VARCHAR (200) NOT NULL
);

CREATE TABLE IF NOT EXISTS workerHead (
id SERIAL PRIMARY KEY,
worker_id INTEGER NOT NULL REFERENCES worker(id),
head_id INTEGER NOT NULL REFERENCES head(id)
);
